# Generated by Django 5.2.17 on 2026-09-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('site', 'Site Update'), ('client', 'Client'), ('supplier', 'Supplier')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
