# Generated by Django 5.2.17 on 2026-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='communication',
            name='decisions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='communication',
            name='risks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
